name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: rockylinux/rockylinux:8

    steps:
      - uses: actions/checkout@v4
      - name: Build dkms
        run: |
          cd ..
          dnf install -y epel-release
          dnf install -y dkms git
          mv daos-kernel /usr/src/daos-kernel-0.1
          dkms build daos-kernel/0.1
          dkms install daos-kernel/0.1
